// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("kartica")]
public partial class Kartica
{
    [Column("stanje", TypeName = "decimal(18, 0)")]
    public decimal Stanje { get; set; }

    [Key]
    [Column("brKartice")]
    public int BrKartice { get; set; }

    [InverseProperty("BrKarticeNavigation")]
    public virtual ICollection<Projekt> Projekt { get; set; } = new List<Projekt>();

    [InverseProperty("BrKarticeNavigation")]
    public virtual ICollection<Transakcija> Transakcija { get; set; } = new List<Transakcija>();
}