// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("osoba")]
public partial class Osoba
{
    [Required]
    [Column("ime", TypeName = "text")]
    public string Ime { get; set; }

    [Key]
    [Column("idOsoba")]
    public int IdOsoba { get; set; }

    [Required]
    [Column("email", TypeName = "text")]
    public string Email { get; set; }

    [Column("telefon")]
    public string Telefon { get; set; }

    [Column("IBAN", TypeName = "text")]
    public string Iban { get; set; }

    [Required]
    [Column("prezime", TypeName = "text")]
    public string Prezime { get; set; }

    [Column("idPartnera")]
    public int? IdPartnera { get; set; }

    [ForeignKey("IdPartnera")]
    [InverseProperty("Osoba")]
    public virtual Partner IdPartneraNavigation { get; set; }

    [InverseProperty("IdOsobaNavigation")]
    public virtual ICollection<RadiNa> RadiNa { get; set; } = new List<RadiNa>();

    [InverseProperty("IdOsobaNavigation")]
    public virtual ICollection<Zadatak> Zadatak { get; set; } = new List<Zadatak>();

    [ForeignKey("IdOsoba")]
    [InverseProperty("IdOsoba")]
    public virtual ICollection<Posao> IdPosla { get; set; } = new List<Posao>();
}