// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("partner")]
[Index("Oib", Name = "UQ__partner__CB394B3E95C7A891", IsUnique = true)]
public partial class Partner
{
    [Column("OIB")]
    public int Oib { get; set; }

    [Required]
    [Column("email", TypeName = "text")]
    public string Email { get; set; }

    [Column("telefon")]
    public int Telefon { get; set; }

    [Column("IBAN", TypeName = "text")]
    public string Iban { get; set; }

    [Required]
    [Column("ime", TypeName = "text")]
    public string Ime { get; set; }

    [Column("adresa", TypeName = "text")]
    public string Adresa { get; set; }

    [Key]
    [Column("idPartnera")]
    public int IdPartnera { get; set; }

    [InverseProperty("IdPartneraNavigation")]
    public virtual ICollection<Osoba> Osoba { get; set; } = new List<Osoba>();

    [ForeignKey("IdPartnera")]
    [InverseProperty("IdPartnera")]
    public virtual ICollection<Projekt> IdProjekta { get; set; } = new List<Projekt>();
}