// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("posao")]
public partial class Posao
{
    [Key]
    [Column("idPosla")]
    public int IdPosla { get; set; }

    [Column("opis", TypeName = "text")]
    public string Opis { get; set; }

    [Required]
    [Column("imePosla", TypeName = "text")]
    public string ImePosla { get; set; }

    [Column("idVrste")]
    public int IdVrste { get; set; }

    [ForeignKey("IdVrste")]
    [InverseProperty("Posao")]
    public virtual VrstaPosla IdVrsteNavigation { get; set; }

    [ForeignKey("IdPosla")]
    [InverseProperty("IdPosla")]
    public virtual ICollection<Osoba> IdOsoba { get; set; } = new List<Osoba>();
}