// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("transakcija")]
public partial class Transakcija
{
    [Column("model", TypeName = "text")]
    public string Model { get; set; }

    [Key]
    [Column("idTrans")]
    public int IdTrans { get; set; }

    [Column("opis", TypeName = "text")]
    public string Opis { get; set; }

    [Column("iznos", TypeName = "decimal(18, 0)")]
    public decimal Iznos { get; set; }

    [Column("datum", TypeName = "datetime")]
    public DateTime? Datum { get; set; }

    [Column("pozivNaBr")]
    public int? PozivNaBr { get; set; }

    [Column("brKartice")]
    public int BrKartice { get; set; }

    [Column("idVrste")]
    public int IdVrste { get; set; }

    [ForeignKey("BrKartice")]
    [InverseProperty("Transakcija")]
    public virtual Kartica BrKarticeNavigation { get; set; }

    [ForeignKey("IdVrste")]
    [InverseProperty("Transakcija")]
    public virtual VrstaTransakcije IdVrsteNavigation { get; set; }
}