// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("uloga")]
public partial class Uloga
{
    [Key]
    [Column("idUloge")]
    public int IdUloge { get; set; }

    [Required]
    [Column("imeUloge", TypeName = "text")]
    public string ImeUloge { get; set; }

    [Column("opis", TypeName = "text")]
    public string Opis { get; set; }

    [Column("idVrste")]
    public int IdVrste { get; set; }

    [ForeignKey("IdVrste")]
    [InverseProperty("Uloga")]
    public virtual VrstaUloge IdVrsteNavigation { get; set; }

    [InverseProperty("IdUlogeNavigation")]
    public virtual ICollection<RadiNa> RadiNa { get; set; } = new List<RadiNa>();
}