// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("vrstaUloge")]
public partial class VrstaUloge
{
    [Key]
    [Column("idVrste")]
    public int IdVrste { get; set; }

    [Required]
    [Column("imeVrste", TypeName = "text")]
    public string ImeVrste { get; set; }

    [InverseProperty("IdVrsteNavigation")]
    public virtual ICollection<Uloga> Uloga { get; set; } = new List<Uloga>();
}