// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RPPP_WebApp.Models;

[Table("vrstaTransakcije")]
public partial class VrstaTransakcije
{
    [Required]
    [Column("imeVrste", TypeName = "text")]
    public string ImeVrste { get; set; }

    [Key]
    [Column("idVrste")]
    public int IdVrste { get; set; }

    [InverseProperty("IdVrsteNavigation")]
    public virtual ICollection<Transakcija> Transakcija { get; set; } = new List<Transakcija>();
}